/* soapH.h
   Generated by gSOAP 2.7.9d from Service.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE__ns1__DataSet
#define SOAP_TYPE__ns1__DataSet (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__DataSet(struct soap*, const char*, int, const _ns1__DataSet *, const char*);
SOAP_FMAC3 _ns1__DataSet * SOAP_FMAC4 soap_get__ns1__DataSet(struct soap*, _ns1__DataSet *, const char*, const char*);
SOAP_FMAC3 _ns1__DataSet * SOAP_FMAC4 soap_in__ns1__DataSet(struct soap*, const char*, _ns1__DataSet *, const char*);
SOAP_FMAC5 _ns1__DataSet * SOAP_FMAC6 soap_new__ns1__DataSet(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__DataSet(struct soap*, _ns1__DataSet*);
SOAP_FMAC3 _ns1__DataSet * SOAP_FMAC4 soap_instantiate__ns1__DataSet(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__DataSet(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE__ns1__getWeatherbyCityNameProResponse
#define SOAP_TYPE__ns1__getWeatherbyCityNameProResponse (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getWeatherbyCityNameProResponse(struct soap*, const char*, int, const _ns1__getWeatherbyCityNameProResponse *, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNameProResponse * SOAP_FMAC4 soap_get__ns1__getWeatherbyCityNameProResponse(struct soap*, _ns1__getWeatherbyCityNameProResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNameProResponse * SOAP_FMAC4 soap_in__ns1__getWeatherbyCityNameProResponse(struct soap*, const char*, _ns1__getWeatherbyCityNameProResponse *, const char*);
SOAP_FMAC5 _ns1__getWeatherbyCityNameProResponse * SOAP_FMAC6 soap_new__ns1__getWeatherbyCityNameProResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getWeatherbyCityNameProResponse(struct soap*, _ns1__getWeatherbyCityNameProResponse*);
SOAP_FMAC3 _ns1__getWeatherbyCityNameProResponse * SOAP_FMAC4 soap_instantiate__ns1__getWeatherbyCityNameProResponse(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getWeatherbyCityNameProResponse(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE__ns1__getWeatherbyCityNamePro
#define SOAP_TYPE__ns1__getWeatherbyCityNamePro (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getWeatherbyCityNamePro(struct soap*, const char*, int, const _ns1__getWeatherbyCityNamePro *, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNamePro * SOAP_FMAC4 soap_get__ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro *, const char*, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNamePro * SOAP_FMAC4 soap_in__ns1__getWeatherbyCityNamePro(struct soap*, const char*, _ns1__getWeatherbyCityNamePro *, const char*);
SOAP_FMAC5 _ns1__getWeatherbyCityNamePro * SOAP_FMAC6 soap_new__ns1__getWeatherbyCityNamePro(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro*);
SOAP_FMAC3 _ns1__getWeatherbyCityNamePro * SOAP_FMAC4 soap_instantiate__ns1__getWeatherbyCityNamePro(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getWeatherbyCityNamePro(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE__ns1__getWeatherbyCityNameResponse
#define SOAP_TYPE__ns1__getWeatherbyCityNameResponse (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getWeatherbyCityNameResponse(struct soap*, const char*, int, const _ns1__getWeatherbyCityNameResponse *, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNameResponse * SOAP_FMAC4 soap_get__ns1__getWeatherbyCityNameResponse(struct soap*, _ns1__getWeatherbyCityNameResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNameResponse * SOAP_FMAC4 soap_in__ns1__getWeatherbyCityNameResponse(struct soap*, const char*, _ns1__getWeatherbyCityNameResponse *, const char*);
SOAP_FMAC5 _ns1__getWeatherbyCityNameResponse * SOAP_FMAC6 soap_new__ns1__getWeatherbyCityNameResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getWeatherbyCityNameResponse(struct soap*, _ns1__getWeatherbyCityNameResponse*);
SOAP_FMAC3 _ns1__getWeatherbyCityNameResponse * SOAP_FMAC4 soap_instantiate__ns1__getWeatherbyCityNameResponse(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getWeatherbyCityNameResponse(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE__ns1__getWeatherbyCityName
#define SOAP_TYPE__ns1__getWeatherbyCityName (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getWeatherbyCityName(struct soap*, const char*, int, const _ns1__getWeatherbyCityName *, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityName * SOAP_FMAC4 soap_get__ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName *, const char*, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityName * SOAP_FMAC4 soap_in__ns1__getWeatherbyCityName(struct soap*, const char*, _ns1__getWeatherbyCityName *, const char*);
SOAP_FMAC5 _ns1__getWeatherbyCityName * SOAP_FMAC6 soap_new__ns1__getWeatherbyCityName(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName*);
SOAP_FMAC3 _ns1__getWeatherbyCityName * SOAP_FMAC4 soap_instantiate__ns1__getWeatherbyCityName(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getWeatherbyCityName(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE__ns1__getSupportDataSetResponse
#define SOAP_TYPE__ns1__getSupportDataSetResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportDataSetResponse(struct soap*, const char*, int, const _ns1__getSupportDataSetResponse *, const char*);
SOAP_FMAC3 _ns1__getSupportDataSetResponse * SOAP_FMAC4 soap_get__ns1__getSupportDataSetResponse(struct soap*, _ns1__getSupportDataSetResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportDataSetResponse * SOAP_FMAC4 soap_in__ns1__getSupportDataSetResponse(struct soap*, const char*, _ns1__getSupportDataSetResponse *, const char*);
SOAP_FMAC5 _ns1__getSupportDataSetResponse * SOAP_FMAC6 soap_new__ns1__getSupportDataSetResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getSupportDataSetResponse(struct soap*, _ns1__getSupportDataSetResponse*);
SOAP_FMAC3 _ns1__getSupportDataSetResponse * SOAP_FMAC4 soap_instantiate__ns1__getSupportDataSetResponse(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportDataSetResponse(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE__ns1__getSupportDataSet
#define SOAP_TYPE__ns1__getSupportDataSet (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportDataSet(struct soap*, const char*, int, const _ns1__getSupportDataSet *, const char*);
SOAP_FMAC3 _ns1__getSupportDataSet * SOAP_FMAC4 soap_get__ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet *, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportDataSet * SOAP_FMAC4 soap_in__ns1__getSupportDataSet(struct soap*, const char*, _ns1__getSupportDataSet *, const char*);
SOAP_FMAC5 _ns1__getSupportDataSet * SOAP_FMAC6 soap_new__ns1__getSupportDataSet(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet*);
SOAP_FMAC3 _ns1__getSupportDataSet * SOAP_FMAC4 soap_instantiate__ns1__getSupportDataSet(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportDataSet(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE__ns1__getSupportProvinceResponse
#define SOAP_TYPE__ns1__getSupportProvinceResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportProvinceResponse(struct soap*, const char*, int, const _ns1__getSupportProvinceResponse *, const char*);
SOAP_FMAC3 _ns1__getSupportProvinceResponse * SOAP_FMAC4 soap_get__ns1__getSupportProvinceResponse(struct soap*, _ns1__getSupportProvinceResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportProvinceResponse * SOAP_FMAC4 soap_in__ns1__getSupportProvinceResponse(struct soap*, const char*, _ns1__getSupportProvinceResponse *, const char*);
SOAP_FMAC5 _ns1__getSupportProvinceResponse * SOAP_FMAC6 soap_new__ns1__getSupportProvinceResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getSupportProvinceResponse(struct soap*, _ns1__getSupportProvinceResponse*);
SOAP_FMAC3 _ns1__getSupportProvinceResponse * SOAP_FMAC4 soap_instantiate__ns1__getSupportProvinceResponse(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportProvinceResponse(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE__ns1__getSupportProvince
#define SOAP_TYPE__ns1__getSupportProvince (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportProvince(struct soap*, const char*, int, const _ns1__getSupportProvince *, const char*);
SOAP_FMAC3 _ns1__getSupportProvince * SOAP_FMAC4 soap_get__ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince *, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportProvince * SOAP_FMAC4 soap_in__ns1__getSupportProvince(struct soap*, const char*, _ns1__getSupportProvince *, const char*);
SOAP_FMAC5 _ns1__getSupportProvince * SOAP_FMAC6 soap_new__ns1__getSupportProvince(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince*);
SOAP_FMAC3 _ns1__getSupportProvince * SOAP_FMAC4 soap_instantiate__ns1__getSupportProvince(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportProvince(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE__ns1__getSupportCityResponse
#define SOAP_TYPE__ns1__getSupportCityResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportCityResponse(struct soap*, const char*, int, const _ns1__getSupportCityResponse *, const char*);
SOAP_FMAC3 _ns1__getSupportCityResponse * SOAP_FMAC4 soap_get__ns1__getSupportCityResponse(struct soap*, _ns1__getSupportCityResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportCityResponse * SOAP_FMAC4 soap_in__ns1__getSupportCityResponse(struct soap*, const char*, _ns1__getSupportCityResponse *, const char*);
SOAP_FMAC5 _ns1__getSupportCityResponse * SOAP_FMAC6 soap_new__ns1__getSupportCityResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getSupportCityResponse(struct soap*, _ns1__getSupportCityResponse*);
SOAP_FMAC3 _ns1__getSupportCityResponse * SOAP_FMAC4 soap_instantiate__ns1__getSupportCityResponse(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportCityResponse(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE__ns1__getSupportCity
#define SOAP_TYPE__ns1__getSupportCity (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportCity(struct soap*, const char*, int, const _ns1__getSupportCity *, const char*);
SOAP_FMAC3 _ns1__getSupportCity * SOAP_FMAC4 soap_get__ns1__getSupportCity(struct soap*, _ns1__getSupportCity *, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportCity * SOAP_FMAC4 soap_in__ns1__getSupportCity(struct soap*, const char*, _ns1__getSupportCity *, const char*);
SOAP_FMAC5 _ns1__getSupportCity * SOAP_FMAC6 soap_new__ns1__getSupportCity(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getSupportCity(struct soap*, _ns1__getSupportCity*);
SOAP_FMAC3 _ns1__getSupportCity * SOAP_FMAC4 soap_instantiate__ns1__getSupportCity(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportCity(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE_ns1__ArrayOfString
#define SOAP_TYPE_ns1__ArrayOfString (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfString(struct soap*, const char*, int, const ns1__ArrayOfString *, const char*);
SOAP_FMAC3 ns1__ArrayOfString * SOAP_FMAC4 soap_get_ns1__ArrayOfString(struct soap*, ns1__ArrayOfString *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfString * SOAP_FMAC4 soap_in_ns1__ArrayOfString(struct soap*, const char*, ns1__ArrayOfString *, const char*);
SOAP_FMAC5 ns1__ArrayOfString * SOAP_FMAC6 soap_new_ns1__ArrayOfString(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__ArrayOfString(struct soap*, ns1__ArrayOfString*);
SOAP_FMAC3 ns1__ArrayOfString * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfString(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfString(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#endif

#ifndef SOAP_TYPE___ns1__getWeatherbyCityNamePro_
#define SOAP_TYPE___ns1__getWeatherbyCityNamePro_ (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getWeatherbyCityNamePro_(struct soap*, struct __ns1__getWeatherbyCityNamePro_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getWeatherbyCityNamePro_(struct soap*, const struct __ns1__getWeatherbyCityNamePro_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getWeatherbyCityNamePro_(struct soap*, const struct __ns1__getWeatherbyCityNamePro_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getWeatherbyCityNamePro_(struct soap*, const char*, int, const struct __ns1__getWeatherbyCityNamePro_ *, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityNamePro_ * SOAP_FMAC4 soap_get___ns1__getWeatherbyCityNamePro_(struct soap*, struct __ns1__getWeatherbyCityNamePro_ *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityNamePro_ * SOAP_FMAC4 soap_in___ns1__getWeatherbyCityNamePro_(struct soap*, const char*, struct __ns1__getWeatherbyCityNamePro_ *, const char*);
SOAP_FMAC5 struct __ns1__getWeatherbyCityNamePro_ * SOAP_FMAC6 soap_new___ns1__getWeatherbyCityNamePro_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__getWeatherbyCityNamePro_(struct soap*, struct __ns1__getWeatherbyCityNamePro_*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityNamePro_ * SOAP_FMAC4 soap_instantiate___ns1__getWeatherbyCityNamePro_(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getWeatherbyCityNamePro_(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE___ns1__getWeatherbyCityName_
#define SOAP_TYPE___ns1__getWeatherbyCityName_ (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getWeatherbyCityName_(struct soap*, struct __ns1__getWeatherbyCityName_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getWeatherbyCityName_(struct soap*, const struct __ns1__getWeatherbyCityName_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getWeatherbyCityName_(struct soap*, const struct __ns1__getWeatherbyCityName_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getWeatherbyCityName_(struct soap*, const char*, int, const struct __ns1__getWeatherbyCityName_ *, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityName_ * SOAP_FMAC4 soap_get___ns1__getWeatherbyCityName_(struct soap*, struct __ns1__getWeatherbyCityName_ *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityName_ * SOAP_FMAC4 soap_in___ns1__getWeatherbyCityName_(struct soap*, const char*, struct __ns1__getWeatherbyCityName_ *, const char*);
SOAP_FMAC5 struct __ns1__getWeatherbyCityName_ * SOAP_FMAC6 soap_new___ns1__getWeatherbyCityName_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__getWeatherbyCityName_(struct soap*, struct __ns1__getWeatherbyCityName_*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityName_ * SOAP_FMAC4 soap_instantiate___ns1__getWeatherbyCityName_(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getWeatherbyCityName_(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE___ns1__getSupportDataSet_
#define SOAP_TYPE___ns1__getSupportDataSet_ (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportDataSet_(struct soap*, struct __ns1__getSupportDataSet_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportDataSet_(struct soap*, const struct __ns1__getSupportDataSet_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportDataSet_(struct soap*, const struct __ns1__getSupportDataSet_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportDataSet_(struct soap*, const char*, int, const struct __ns1__getSupportDataSet_ *, const char*);
SOAP_FMAC3 struct __ns1__getSupportDataSet_ * SOAP_FMAC4 soap_get___ns1__getSupportDataSet_(struct soap*, struct __ns1__getSupportDataSet_ *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getSupportDataSet_ * SOAP_FMAC4 soap_in___ns1__getSupportDataSet_(struct soap*, const char*, struct __ns1__getSupportDataSet_ *, const char*);
SOAP_FMAC5 struct __ns1__getSupportDataSet_ * SOAP_FMAC6 soap_new___ns1__getSupportDataSet_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__getSupportDataSet_(struct soap*, struct __ns1__getSupportDataSet_*);
SOAP_FMAC3 struct __ns1__getSupportDataSet_ * SOAP_FMAC4 soap_instantiate___ns1__getSupportDataSet_(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportDataSet_(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE___ns1__getSupportProvince_
#define SOAP_TYPE___ns1__getSupportProvince_ (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportProvince_(struct soap*, struct __ns1__getSupportProvince_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportProvince_(struct soap*, const struct __ns1__getSupportProvince_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportProvince_(struct soap*, const struct __ns1__getSupportProvince_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportProvince_(struct soap*, const char*, int, const struct __ns1__getSupportProvince_ *, const char*);
SOAP_FMAC3 struct __ns1__getSupportProvince_ * SOAP_FMAC4 soap_get___ns1__getSupportProvince_(struct soap*, struct __ns1__getSupportProvince_ *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getSupportProvince_ * SOAP_FMAC4 soap_in___ns1__getSupportProvince_(struct soap*, const char*, struct __ns1__getSupportProvince_ *, const char*);
SOAP_FMAC5 struct __ns1__getSupportProvince_ * SOAP_FMAC6 soap_new___ns1__getSupportProvince_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__getSupportProvince_(struct soap*, struct __ns1__getSupportProvince_*);
SOAP_FMAC3 struct __ns1__getSupportProvince_ * SOAP_FMAC4 soap_instantiate___ns1__getSupportProvince_(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportProvince_(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE___ns1__getSupportCity_
#define SOAP_TYPE___ns1__getSupportCity_ (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportCity_(struct soap*, struct __ns1__getSupportCity_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportCity_(struct soap*, const struct __ns1__getSupportCity_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportCity_(struct soap*, const struct __ns1__getSupportCity_ *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportCity_(struct soap*, const char*, int, const struct __ns1__getSupportCity_ *, const char*);
SOAP_FMAC3 struct __ns1__getSupportCity_ * SOAP_FMAC4 soap_get___ns1__getSupportCity_(struct soap*, struct __ns1__getSupportCity_ *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getSupportCity_ * SOAP_FMAC4 soap_in___ns1__getSupportCity_(struct soap*, const char*, struct __ns1__getSupportCity_ *, const char*);
SOAP_FMAC5 struct __ns1__getSupportCity_ * SOAP_FMAC6 soap_new___ns1__getSupportCity_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__getSupportCity_(struct soap*, struct __ns1__getSupportCity_*);
SOAP_FMAC3 struct __ns1__getSupportCity_ * SOAP_FMAC4 soap_instantiate___ns1__getSupportCity_(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportCity_(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE___ns1__getWeatherbyCityNamePro
#define SOAP_TYPE___ns1__getWeatherbyCityNamePro (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getWeatherbyCityNamePro(struct soap*, struct __ns1__getWeatherbyCityNamePro *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getWeatherbyCityNamePro(struct soap*, const struct __ns1__getWeatherbyCityNamePro *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getWeatherbyCityNamePro(struct soap*, const struct __ns1__getWeatherbyCityNamePro *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getWeatherbyCityNamePro(struct soap*, const char*, int, const struct __ns1__getWeatherbyCityNamePro *, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityNamePro * SOAP_FMAC4 soap_get___ns1__getWeatherbyCityNamePro(struct soap*, struct __ns1__getWeatherbyCityNamePro *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityNamePro * SOAP_FMAC4 soap_in___ns1__getWeatherbyCityNamePro(struct soap*, const char*, struct __ns1__getWeatherbyCityNamePro *, const char*);
SOAP_FMAC5 struct __ns1__getWeatherbyCityNamePro * SOAP_FMAC6 soap_new___ns1__getWeatherbyCityNamePro(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__getWeatherbyCityNamePro(struct soap*, struct __ns1__getWeatherbyCityNamePro*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityNamePro * SOAP_FMAC4 soap_instantiate___ns1__getWeatherbyCityNamePro(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getWeatherbyCityNamePro(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE___ns1__getWeatherbyCityName
#define SOAP_TYPE___ns1__getWeatherbyCityName (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getWeatherbyCityName(struct soap*, struct __ns1__getWeatherbyCityName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getWeatherbyCityName(struct soap*, const struct __ns1__getWeatherbyCityName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getWeatherbyCityName(struct soap*, const struct __ns1__getWeatherbyCityName *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getWeatherbyCityName(struct soap*, const char*, int, const struct __ns1__getWeatherbyCityName *, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityName * SOAP_FMAC4 soap_get___ns1__getWeatherbyCityName(struct soap*, struct __ns1__getWeatherbyCityName *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityName * SOAP_FMAC4 soap_in___ns1__getWeatherbyCityName(struct soap*, const char*, struct __ns1__getWeatherbyCityName *, const char*);
SOAP_FMAC5 struct __ns1__getWeatherbyCityName * SOAP_FMAC6 soap_new___ns1__getWeatherbyCityName(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__getWeatherbyCityName(struct soap*, struct __ns1__getWeatherbyCityName*);
SOAP_FMAC3 struct __ns1__getWeatherbyCityName * SOAP_FMAC4 soap_instantiate___ns1__getWeatherbyCityName(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getWeatherbyCityName(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE___ns1__getSupportDataSet
#define SOAP_TYPE___ns1__getSupportDataSet (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportDataSet(struct soap*, struct __ns1__getSupportDataSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportDataSet(struct soap*, const struct __ns1__getSupportDataSet *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportDataSet(struct soap*, const struct __ns1__getSupportDataSet *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportDataSet(struct soap*, const char*, int, const struct __ns1__getSupportDataSet *, const char*);
SOAP_FMAC3 struct __ns1__getSupportDataSet * SOAP_FMAC4 soap_get___ns1__getSupportDataSet(struct soap*, struct __ns1__getSupportDataSet *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getSupportDataSet * SOAP_FMAC4 soap_in___ns1__getSupportDataSet(struct soap*, const char*, struct __ns1__getSupportDataSet *, const char*);
SOAP_FMAC5 struct __ns1__getSupportDataSet * SOAP_FMAC6 soap_new___ns1__getSupportDataSet(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__getSupportDataSet(struct soap*, struct __ns1__getSupportDataSet*);
SOAP_FMAC3 struct __ns1__getSupportDataSet * SOAP_FMAC4 soap_instantiate___ns1__getSupportDataSet(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportDataSet(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE___ns1__getSupportProvince
#define SOAP_TYPE___ns1__getSupportProvince (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportProvince(struct soap*, struct __ns1__getSupportProvince *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportProvince(struct soap*, const struct __ns1__getSupportProvince *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportProvince(struct soap*, const struct __ns1__getSupportProvince *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportProvince(struct soap*, const char*, int, const struct __ns1__getSupportProvince *, const char*);
SOAP_FMAC3 struct __ns1__getSupportProvince * SOAP_FMAC4 soap_get___ns1__getSupportProvince(struct soap*, struct __ns1__getSupportProvince *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getSupportProvince * SOAP_FMAC4 soap_in___ns1__getSupportProvince(struct soap*, const char*, struct __ns1__getSupportProvince *, const char*);
SOAP_FMAC5 struct __ns1__getSupportProvince * SOAP_FMAC6 soap_new___ns1__getSupportProvince(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__getSupportProvince(struct soap*, struct __ns1__getSupportProvince*);
SOAP_FMAC3 struct __ns1__getSupportProvince * SOAP_FMAC4 soap_instantiate___ns1__getSupportProvince(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportProvince(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE___ns1__getSupportCity
#define SOAP_TYPE___ns1__getSupportCity (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getSupportCity(struct soap*, struct __ns1__getSupportCity *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getSupportCity(struct soap*, const struct __ns1__getSupportCity *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getSupportCity(struct soap*, const struct __ns1__getSupportCity *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getSupportCity(struct soap*, const char*, int, const struct __ns1__getSupportCity *, const char*);
SOAP_FMAC3 struct __ns1__getSupportCity * SOAP_FMAC4 soap_get___ns1__getSupportCity(struct soap*, struct __ns1__getSupportCity *, const char*, const char*);
SOAP_FMAC3 struct __ns1__getSupportCity * SOAP_FMAC4 soap_in___ns1__getSupportCity(struct soap*, const char*, struct __ns1__getSupportCity *, const char*);
SOAP_FMAC5 struct __ns1__getSupportCity * SOAP_FMAC6 soap_new___ns1__getSupportCity(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns1__getSupportCity(struct soap*, struct __ns1__getSupportCity*);
SOAP_FMAC3 struct __ns1__getSupportCity * SOAP_FMAC4 soap_instantiate___ns1__getSupportCity(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getSupportCity(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef SOAP_TYPE__ns1__getSupportDataSetResponse_getSupportDataSetResult
#define SOAP_TYPE__ns1__getSupportDataSetResponse_getSupportDataSetResult (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, struct _ns1__getSupportDataSetResponse_getSupportDataSetResult *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, const struct _ns1__getSupportDataSetResponse_getSupportDataSetResult *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, const struct _ns1__getSupportDataSetResponse_getSupportDataSetResult *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, const char*, int, const struct _ns1__getSupportDataSetResponse_getSupportDataSetResult *, const char*);
SOAP_FMAC3 struct _ns1__getSupportDataSetResponse_getSupportDataSetResult * SOAP_FMAC4 soap_get__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, struct _ns1__getSupportDataSetResponse_getSupportDataSetResult *, const char*, const char*);
SOAP_FMAC3 struct _ns1__getSupportDataSetResponse_getSupportDataSetResult * SOAP_FMAC4 soap_in__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, const char*, struct _ns1__getSupportDataSetResponse_getSupportDataSetResult *, const char*);
SOAP_FMAC5 struct _ns1__getSupportDataSetResponse_getSupportDataSetResult * SOAP_FMAC6 soap_new__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, struct _ns1__getSupportDataSetResponse_getSupportDataSetResult*);
SOAP_FMAC3 struct _ns1__getSupportDataSetResponse_getSupportDataSetResult * SOAP_FMAC4 soap_instantiate__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, int, const char*, const char*, size_t*);
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, int, int, void*, size_t, const void*, size_t);
#ifdef __cplusplus
}
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__getWeatherbyCityNameProResponse
#define SOAP_TYPE_PointerTo_ns1__getWeatherbyCityNameProResponse (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getWeatherbyCityNameProResponse(struct soap*, _ns1__getWeatherbyCityNameProResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getWeatherbyCityNameProResponse(struct soap*, _ns1__getWeatherbyCityNameProResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getWeatherbyCityNameProResponse(struct soap*, const char *, int, _ns1__getWeatherbyCityNameProResponse *const*, const char *);
SOAP_FMAC3 _ns1__getWeatherbyCityNameProResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getWeatherbyCityNameProResponse(struct soap*, _ns1__getWeatherbyCityNameProResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNameProResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getWeatherbyCityNameProResponse(struct soap*, const char*, _ns1__getWeatherbyCityNameProResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getWeatherbyCityNamePro
#define SOAP_TYPE_PointerTo_ns1__getWeatherbyCityNamePro (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getWeatherbyCityNamePro(struct soap*, const char *, int, _ns1__getWeatherbyCityNamePro *const*, const char *);
SOAP_FMAC3 _ns1__getWeatherbyCityNamePro ** SOAP_FMAC4 soap_get_PointerTo_ns1__getWeatherbyCityNamePro(struct soap*, _ns1__getWeatherbyCityNamePro **, const char*, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNamePro ** SOAP_FMAC4 soap_in_PointerTo_ns1__getWeatherbyCityNamePro(struct soap*, const char*, _ns1__getWeatherbyCityNamePro **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getWeatherbyCityNameResponse
#define SOAP_TYPE_PointerTo_ns1__getWeatherbyCityNameResponse (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getWeatherbyCityNameResponse(struct soap*, _ns1__getWeatherbyCityNameResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getWeatherbyCityNameResponse(struct soap*, _ns1__getWeatherbyCityNameResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getWeatherbyCityNameResponse(struct soap*, const char *, int, _ns1__getWeatherbyCityNameResponse *const*, const char *);
SOAP_FMAC3 _ns1__getWeatherbyCityNameResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getWeatherbyCityNameResponse(struct soap*, _ns1__getWeatherbyCityNameResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityNameResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getWeatherbyCityNameResponse(struct soap*, const char*, _ns1__getWeatherbyCityNameResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getWeatherbyCityName
#define SOAP_TYPE_PointerTo_ns1__getWeatherbyCityName (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getWeatherbyCityName(struct soap*, const char *, int, _ns1__getWeatherbyCityName *const*, const char *);
SOAP_FMAC3 _ns1__getWeatherbyCityName ** SOAP_FMAC4 soap_get_PointerTo_ns1__getWeatherbyCityName(struct soap*, _ns1__getWeatherbyCityName **, const char*, const char*);
SOAP_FMAC3 _ns1__getWeatherbyCityName ** SOAP_FMAC4 soap_in_PointerTo_ns1__getWeatherbyCityName(struct soap*, const char*, _ns1__getWeatherbyCityName **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getSupportDataSetResponse
#define SOAP_TYPE_PointerTo_ns1__getSupportDataSetResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getSupportDataSetResponse(struct soap*, _ns1__getSupportDataSetResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getSupportDataSetResponse(struct soap*, _ns1__getSupportDataSetResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getSupportDataSetResponse(struct soap*, const char *, int, _ns1__getSupportDataSetResponse *const*, const char *);
SOAP_FMAC3 _ns1__getSupportDataSetResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getSupportDataSetResponse(struct soap*, _ns1__getSupportDataSetResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportDataSetResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getSupportDataSetResponse(struct soap*, const char*, _ns1__getSupportDataSetResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getSupportDataSet
#define SOAP_TYPE_PointerTo_ns1__getSupportDataSet (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getSupportDataSet(struct soap*, const char *, int, _ns1__getSupportDataSet *const*, const char *);
SOAP_FMAC3 _ns1__getSupportDataSet ** SOAP_FMAC4 soap_get_PointerTo_ns1__getSupportDataSet(struct soap*, _ns1__getSupportDataSet **, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportDataSet ** SOAP_FMAC4 soap_in_PointerTo_ns1__getSupportDataSet(struct soap*, const char*, _ns1__getSupportDataSet **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getSupportProvinceResponse
#define SOAP_TYPE_PointerTo_ns1__getSupportProvinceResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getSupportProvinceResponse(struct soap*, _ns1__getSupportProvinceResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getSupportProvinceResponse(struct soap*, _ns1__getSupportProvinceResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getSupportProvinceResponse(struct soap*, const char *, int, _ns1__getSupportProvinceResponse *const*, const char *);
SOAP_FMAC3 _ns1__getSupportProvinceResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getSupportProvinceResponse(struct soap*, _ns1__getSupportProvinceResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportProvinceResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getSupportProvinceResponse(struct soap*, const char*, _ns1__getSupportProvinceResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getSupportProvince
#define SOAP_TYPE_PointerTo_ns1__getSupportProvince (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getSupportProvince(struct soap*, const char *, int, _ns1__getSupportProvince *const*, const char *);
SOAP_FMAC3 _ns1__getSupportProvince ** SOAP_FMAC4 soap_get_PointerTo_ns1__getSupportProvince(struct soap*, _ns1__getSupportProvince **, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportProvince ** SOAP_FMAC4 soap_in_PointerTo_ns1__getSupportProvince(struct soap*, const char*, _ns1__getSupportProvince **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getSupportCityResponse
#define SOAP_TYPE_PointerTo_ns1__getSupportCityResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getSupportCityResponse(struct soap*, _ns1__getSupportCityResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getSupportCityResponse(struct soap*, _ns1__getSupportCityResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getSupportCityResponse(struct soap*, const char *, int, _ns1__getSupportCityResponse *const*, const char *);
SOAP_FMAC3 _ns1__getSupportCityResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__getSupportCityResponse(struct soap*, _ns1__getSupportCityResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportCityResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__getSupportCityResponse(struct soap*, const char*, _ns1__getSupportCityResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getSupportCity
#define SOAP_TYPE_PointerTo_ns1__getSupportCity (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getSupportCity(struct soap*, _ns1__getSupportCity *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getSupportCity(struct soap*, _ns1__getSupportCity *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getSupportCity(struct soap*, const char *, int, _ns1__getSupportCity *const*, const char *);
SOAP_FMAC3 _ns1__getSupportCity ** SOAP_FMAC4 soap_get_PointerTo_ns1__getSupportCity(struct soap*, _ns1__getSupportCity **, const char*, const char*);
SOAP_FMAC3 _ns1__getSupportCity ** SOAP_FMAC4 soap_in_PointerTo_ns1__getSupportCity(struct soap*, const char*, _ns1__getSupportCity **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult
#define SOAP_TYPE_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, struct _ns1__getSupportDataSetResponse_getSupportDataSetResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, struct _ns1__getSupportDataSetResponse_getSupportDataSetResult *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, const char *, int, struct _ns1__getSupportDataSetResponse_getSupportDataSetResult *const*, const char *);
SOAP_FMAC3 struct _ns1__getSupportDataSetResponse_getSupportDataSetResult ** SOAP_FMAC4 soap_get_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, struct _ns1__getSupportDataSetResponse_getSupportDataSetResult **, const char*, const char*);
SOAP_FMAC3 struct _ns1__getSupportDataSetResponse_getSupportDataSetResult ** SOAP_FMAC4 soap_in_PointerTo_ns1__getSupportDataSetResponse_getSupportDataSetResult(struct soap*, const char*, struct _ns1__getSupportDataSetResponse_getSupportDataSetResult **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ArrayOfString
#define SOAP_TYPE_PointerTons1__ArrayOfString (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfString(struct soap*, ns1__ArrayOfString *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfString(struct soap*, ns1__ArrayOfString *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfString(struct soap*, const char *, int, ns1__ArrayOfString *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfString ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfString(struct soap*, ns1__ArrayOfString **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfString ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfString(struct soap*, const char*, ns1__ArrayOfString **, const char*);

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE__xsd__schema
#define SOAP_TYPE__xsd__schema (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__xsd__schema(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__xsd__schema(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__xsd__schema(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__xsd__schema(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__xsd__schema(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__xsd__schema(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
